#!/bin/bash
# insta485db

# Stop on errors
set -e

# Sanity check command line options
usage() {
  echo "Usage: $0 (create|destroy|reset|dump)"
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi


# Parse argument.  $1 is the first argument
case $1 in
  "reset")
      rm data.sqlite3
      sqlite3 data.sqlite3 < schema.sql
      sqlite3 data.sqlite3 < data.sql
      echo "+ sqlite3 data.sqlite3 < schema.sql"
      echo "+ sqlite3 data.sqlite3 < data.sql"
    fi
    ;;
  *)
    usage
    exit 1
    ;;
esac