CREATE TABLE users(
   username 	VARCHAR(20) 	PRIMARY KEY NOT NULL,
   fullname 	VARCHAR(40) 	NOT NULL,
   email 		VARCHAR(40) 	NOT NULL,
   filename 	VARCHAR(64) 	NOT NULL,
   password 	VARCHAR(256) 	NOT NULL,
   created 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE posts(
	postid		INTEGER 		PRIMARY KEY AUTOINCREMENT,
	filename 	VARCHAR(64) 	NOT NULL,
	owner		VARCHAR(20) 	NOT NULL,
	created 	TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_user
		FOREIGN KEY (owner)
		REFERENCES users (username)
		ON DELETE CASCADE
);

CREATE TABLE following(
	username1	VARCHAR(20) 	NOT NULL,
	username2	VARCHAR(20) 	NOT NULL,
	created 	TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(username1, username2)
);

CREATE TABLE comments(
	commentid 	INTEGER 		PRIMARY KEY AUTOINCREMENT,
	owner		VARCHAR(20)		NOT NULL,
	postid		INT 			NOT NULL,
	text		VARCHAR(1024)	NOT NULL,
	created 	TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_user
		FOREIGN KEY (owner)
		REFERENCES users (username)
		ON DELETE CASCADE
);

CREATE TABLE likes(
	owner		VARCHAR(20),
	postid		INT,
	created 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(owner, postid),
	CONSTRAINT fk_user
		FOREIGN KEY (owner)
		REFERENCES users (username)
		ON DELETE CASCADE
);
